multi_branch_env:
  hostname: tr.rt.gw
  user: root
  site_url: https://karunya-chavan.tr.rt.gw
  main_site: karunya-chavan.tr.rt.gw
  deploy_path: /opt/easyengine/sites/karunya-chavan.tr.rt.gw/app/htdocs
